[package]
name = "simba"
version = "0.1.0"
authors = ["sebcrozet <developer@crozet.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "std" ]
std = [ ]
simd = [ "packed_simd" ]

[dependencies]
num-traits  = { version = "0.2.11", default-features = false, features = ["libm"] }
approx      = { version = "0.3", default-features = false }
decimal     = { version = "2.0", default-features = false, optional = true }
num-complex = { version = "0.2", default-features = false }
packed_simd = { version = "0.3", optional = true }
paste = "0.1"